apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging-http01
  namespace: argocd
spec:
  acme:
    email: shinkay.register@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production-http01
  namespace: argocd
spec:
  acme:
    email: shinkay.register@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
        - http01:
            ingress:
              ingressClassName: traefik